import type { Metadata } from "next";
import "./globals.css";
import { headers } from "next/headers";
import ContextProvider from "./Provider"
import MainHeader from "@/components/main-header";
import { Nunito_Sans } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/context/AuthProvider";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "800", "900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersObj = await headers();
  const cookies = headersObj.get('cookie')
  return (
    <html lang="en">
      <body suppressHydrationWarning
        className={`${nunitoSans.className} antialiased`}
      >
        <Toaster position="top-center" />
        <AuthProvider>
          <ContextProvider cookies={cookies}>
            <MainHeader />
            {children}
          </ContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
